name: weather_forecast_app
description: "Weather Forecast Application"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8

  #riverpod
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1

  #localStorage
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #platform
  go_router: ^14.8.1

  #network
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  equatable: ^2.0.7
  pretty_dio_logger: ^1.4.0
  vexana: ^5.0.3
  dartz: ^0.10.1

  # localization
  easy_localization: ^3.0.7+1
  easy_localization_loader: ^2.0.2


  #utils
  intl: any
  kartal: ^4.1.0
  environment_config: ^4.0.0+1
  easy_logger: ^0.0.2
  logger: ^2.5.0
  google_fonts: ^6.2.1
  geolocator: ^11.0.0
  uuid: ^4.2.1 
  freezed: ^2.3.2
  
  generated:
    path: ./generated
  google_places_flutter: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/languages/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
 