name: generated
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_svg: ^2.1.0
  envied: ^1.1.1
  lottie: ^3.3.1
  dio: ^5.4.0
  flutter_riverpod: ^2.4.0
    #database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  riverpod_annotation: ^2.3.3
  #freezed
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.10.0
  very_good_analysis: ^7.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.7.0
  freezed: ^2.3.2
  envied_generator: ^1.1.1
  riverpod_generator: ^2.3.3
  hive_generator: ^2.0.1

flutter_gen:
  output: lib/source/assets/
  integrations:
    lottie: true
    flutter_svg: true

flutter:
  assets:
    - assets/lottie/
    - assets/icons/
    - assets/images/

