name: generated
description: "A new Flutter package project."
version: 0.0.1
homepage: none
environment:
  sdk: ^3.7.2
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  retrofit: ^4.0.1
  equatable: ^2.0.7
  flutter_svg: ^2.1.0
  envied: ^1.1.1
  lottie: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  freezed: ^2.3.2
  retrofit_generator: ^9.1.9
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  envied_generator: ^1.1.1
  flutter_gen_runner: ^5.10.0
  very_good_analysis: ^7.0.0

flutter_gen:
  output: lib/source/assets/
  integrations:
    lottie: true
    flutter_svg: true

flutter:
  assets:
    - assets/lottie/
    - assets/icons/
    - assets/images/
